"""
Backend API for the Python Documentation Assistant.

Exposes a FastAPI REST interface to process user queries through the RAG pipeline.
"""

import asyncio
import logging
from contextlib import asynccontextmanager
from fastapi import FastAPI, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

# Ensure robust backend exception handling if chatbot imports fall through
try:
    from chatbot import get_response
except ImportError as e:
    raise RuntimeError(
        "Could not import 'get_response' from chatbot.py. Ensure your pipeline files are co-located."
    ) from e

# Configure Logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    handlers=[logging.StreamHandler()]
)
logger = logging.getLogger("backend_api")


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Handles single-instantiation startup logic and shutdown cleanup."""
    logger.info("Initializing Python Documentation Assistant backend services...")
    # Trigger any warm-up steps or lazy loading inside chatbot.py if necessary here
    yield
    logger.info("Shutting down backend services.")


app = FastAPI(
    title="Python Documentation Assistant API",
    version="1.0.0",
    lifespan=lifespan
)

# Enable CORS for frontend integrations (React, Vue, etc.)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Restrict this to specific domains in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# --- Data Models ---
class ChatRequest(BaseModel):
    message: str = Field(
        ..., 
        description="The query question regarding Python documentation.",
        json_schema_extra={
        "example": "What is a list comprehension?"
        },
    )


class ChatResponse(BaseModel):
    answer: str
    status: str = "success"


# --- Endpoints ---
@app.get("/", status_code=status.HTTP_200_OK)
async def read_root():
    """Health check endpoint to confirm API operational status."""
    return {
        "status": "healthy",
        "message": "Python Documentation Assistant API is running smoothly."
    }


@app.post("/chat", response_model=ChatResponse, status_code=status.HTTP_200_OK)
async def chat_endpoint(payload: ChatRequest):
    """
    Processes a incoming user message, queries the local FAISS vector store,
    and returns the structured response generated by the local LLM model.
    """
    # 1. Input string sanitation and validation
    clean_message = payload.message.strip()
    if not clean_message:
        logger.warning("Rejected request: Message field contains only empty whitespace string.")
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_CONTENT,
            detail="The 'message' parameter cannot be empty or solely whitespace."
        )

    logger.info("Incoming request received. Query text length: %d characters", len(clean_message))

    # 2. Pipeline Execution
    try:
        # Run the blocking RAG call in a thread so FastAPI stays responsive.
        answer = await asyncio.to_thread(get_response, clean_message)
        
        logger.info("Successfully generated pipeline response.")
        return ChatResponse(answer=answer, status="success")

    except Exception as exc:
        logger.error("Unexpected pipeline exception raised: %s", str(exc), exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="An unexpected error occurred internally while generating your answer."
        ) from exc